name: Feature Request
description: Suggest a new feature or enhancement
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        **Thank you for suggesting a feature!**
        Please describe your idea in detail.

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: What should be added or improved?

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Explain why this feature would be useful.

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Have you considered other solutions?

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other relevant details?
