FROM ubuntu:24.04

WORKDIR /app

ENV GO_VERSION=1.23.3

RUN apt-get update
RUN apt-get install -y wget git gcc make cmake g++ dpkg pkg-config libdrm-dev python3-wheel python3-setuptools python3-virtualenv

RUN git clone https://github.com/ROCm/amdsmi.git && cd amdsmi && \
mkdir -p build && cd build && cmake .. && make -j $(nproc) && make install \
&& cd /app
RUN git clone https://github.com/amd/amd_hsmp.git \
&& mkdir -p /usr/include/x86_64-linux-gnu/asm \
&& cp ./amd_hsmp/amd_hsmp.h /usr/include/x86_64-linux-gnu/asm/amd_hsmp.h
RUN git clone https://github.com/amd/esmi_ib_library.git && cd esmi_ib_library \
&& mkdir -p build && cd build && cmake ../ && make install && cd /app
RUN git clone https://github.com/ROCm/rocm_smi_lib.git && cd rocm_smi_lib \
&& mkdir -p build && cd build && cmake ../ && make && make install \
&& cd /app
RUN git clone https://github.com/amd/go_amd_smi.git && cd go_amd_smi/goamdsmi_shim \
&& mkdir -p build && cd build && cmake ../amd_smi.cmake ../ \
&& make && make install && cd /app

RUN rm -rf amdsmi amd_hsmp esmi_ib_library rocm_smi_lib goamdsmi_shim

RUN wget -P /tmp "https://dl.google.com/go/go${GO_VERSION}.linux-amd64.tar.gz" \
&& tar -C /usr/local -xzf "/tmp/go${GO_VERSION}.linux-amd64.tar.gz" \
&& rm "/tmp/go${GO_VERSION}.linux-amd64.tar.gz"
ENV GOPATH /go
ENV PATH $GOPATH/bin:/usr/local/go/bin:$PATH
RUN mkdir -p "$GOPATH/src" "$GOPATH/bin" && chmod -R 777 "$GOPATH"